// ═══════════════════════ DATABASE ═══════════════════════
var animeDB=[
  {title:"AKIRA",jp:"アキラ",rating:5,desc:"Neo-Tokyo 2019. Changed animation forever.",tags:["action","scifi"],malId:"47",year:"1988",episodes:"1 movie",status:"finished"},
  {title:"GHOST IN THE SHELL",jp:"攻殻機動隊",rating:4,desc:"Philosophical cyberpunk masterpiece.",tags:["action","scifi","psychological"],malId:"43",year:"1995",episodes:"1 movie",status:"finished"},
  {title:"NEON GENESIS EVANGELION",jp:"新世紀エヴァンゲリオン",rating:4,desc:"Mechs, trauma, existential dread.",tags:["psychological","action","scifi"],malId:"30",year:"1995",episodes:"26 eps + movie",status:"finished"},
  {title:"COWBOY BEBOP",jp:"カウボーイビバップ",rating:4,desc:"Space jazz noir. Best ending ever.",tags:["action","scifi"],malId:"1",year:"1998",episodes:"26 eps",status:"finished"},
  {title:"PERFECT BLUE",jp:"パーフェクトブルー",rating:4,desc:"Satoshi Kon's psychological horror masterpiece.",tags:["psychological"],malId:"486",year:"1997",episodes:"1 movie",status:"finished"},
  {title:"MONSTER",jp:"モンスター",rating:4,desc:"Surgeon hunts serial killer he saved.",tags:["psychological"],malId:"19",year:"2004",episodes:"74 eps",status:"finished"},
  {title:"DEATH NOTE",jp:"デスノート",rating:4,desc:"A notebook that kills. Ultimate cat-and-mouse.",tags:["psychological"],malId:"1535",year:"2006",episodes:"37 eps",status:"finished"},
  {title:"STEINS;GATE",jp:"シュタインズ・ゲート",rating:5,desc:"Time travel and emotional devastation.",tags:["scifi","psychological"],malId:"9253",year:"2011",episodes:"24 eps",status:"finished"},
  {title:"SERIAL EXPERIMENTS LAIN",jp:"シリアルエクスペリメンツレイン",rating:3,desc:"The internet, identity, reality collapsing.",tags:["psychological","scifi"],malId:"339",year:"1998",episodes:"13 eps",status:"finished"},
  {title:"VINLAND SAGA",jp:"ヴィンランド・サガ",rating:4,desc:"Vikings, revenge, and the path to peace.",tags:["action","historical"],malId:"37521",year:"2019",episodes:"48 eps (2 seasons)",status:"finished"},
  {title:"FULLMETAL ALCHEMIST: BROTHERHOOD",jp:"鋼の錬金術師",rating:5,desc:"Equivalent exchange. Definitive shounen.",tags:["action"],malId:"5114",year:"2009",episodes:"64 eps",status:"finished"},
  {title:"ATTACK ON TITAN",jp:"進撃の巨人",rating:4,desc:"Humanity's last stand. Best plot twist in anime.",tags:["action"],malId:"16498",year:"2013",episodes:"87 eps (4 seasons)",status:"finished"},
  {title:"CHAINSAW MAN",jp:"チェンソーマン",rating:4,desc:"Denji and his chainsaw devil. Raw and unfiltered.",tags:["action"],malId:"44511",year:"2022",episodes:"12 eps + movie",status:"finished"},
  {title:"JUJUTSU KAISEN",jp:"呪術廻戦",rating:4,desc:"Curses, sorcery, and insane animation.",tags:["action"],malId:"40748",year:"2020",episodes:"47 eps (2 seasons)",status:"airing"},
  {title:"DEMON SLAYER",jp:"鬼滅の刃",rating:4,desc:"Family, demons, and Ufotable's visual spectacle.",tags:["action"],malId:"38000",year:"2019",episodes:"55 eps + movies",status:"finished"},
  {title:"DANDADAN",jp:"ダンダダン",rating:4,desc:"Ghosts, aliens, and absurd romance. Fresh masterpiece.",tags:["action","romance"],malId:"58340",year:"2024",episodes:"12 eps (S1)",status:"airing"},
  {title:"FRIEREN: BEYOND JOURNEY'S END",jp:"葬送のフリーレン",rating:5,desc:"Elf reflects on mortality after the hero's victory.",tags:["fantasy","drama"],malId:"52991",year:"2023",episodes:"28 eps",status:"finished"},
  {title:"KAGUYA-SAMA: LOVE IS WAR",jp:"かぐや様は告らせたい",rating:4,desc:"Two geniuses play 5D chess to avoid confessing love.",tags:["romance","comedy"],malId:"37999",year:"2019",episodes:"37 eps (3 seasons) + movie",status:"finished"},
  {title:"HORIMIYA",jp:"ホリミヤ",rating:4,desc:"Opposites attract. The most wholesome romance.",tags:["romance","slice-of-life"],malId:"42897",year:"2021",episodes:"13 eps + OVAs",status:"finished"},
  {title:"YOUR LIE IN APRIL",jp:"四月は君の嘘",rating:4,desc:"Music, trauma, and the most devastating tears.",tags:["romance","drama"],malId:"12189",year:"2014",episodes:"22 eps",status:"finished"},
  {title:"SPIRITED AWAY",jp:"千と千尋の神隠し",rating:4,desc:"Ghibli's crown jewel. A girl in the spirit world.",tags:["fantasy","drama"],malId:"199",year:"2001",episodes:"1 movie",status:"finished"},
  {title:"PRINCESS MONONOKE",jp:"もののけ姫",rating:4,desc:"Epic tale of nature vs civilization.",tags:["fantasy","action"],malId:"164",year:"1997",episodes:"1 movie",status:"finished"},
  {title:"HOWL'S MOVING CASTLE",jp:"ハウルの動く城",rating:4,desc:"Magic, war, and an unlikely love story.",tags:["fantasy","romance"],malId:"431",year:"2004",episodes:"1 movie",status:"finished"},
  {title:"GRAVE OF THE FIREFLIES",jp:"火垂るの墓",rating:4,desc:"The most devastating war film ever made.",tags:["drama","historical"],malId:"578",year:"1988",episodes:"1 movie",status:"finished"},
  {title:"YOUR NAME",jp:"君の名は",rating:4,desc:"Body-swap romance that broke records worldwide.",tags:["romance","drama"],malId:"32281",year:"2016",episodes:"1 movie",status:"finished"},
  {title:"A SILENT VOICE",jp:"聲の形",rating:4,desc:"Redemption story about bullying and forgiveness.",tags:["drama","romance"],malId:"28851",year:"2016",episodes:"1 movie",status:"finished"},
  {title:"VIOLET EVERGARDEN",jp:"ヴァイオレット・エヴァーガーデン",rating:4,desc:"A former soldier learns the meaning of love through letters.",tags:["drama","slice-of-life"],malId:"33352",year:"2018",episodes:"13 eps + movie",status:"finished"},
  {title:"MUSHISHI",jp:"蟲師",rating:4,desc:"Ginko wanders studying primordial lifeforms called Mushi.",tags:["slice-of-life","fantasy"],malId:"457",year:"2005",episodes:"46 eps (2 seasons)",status:"finished"},
  {title:"MARCH COMES IN LIKE A LION",jp:"3月のライオン",rating:4,desc:"Shogi prodigy battles depression and finds family.",tags:["drama","slice-of-life"],malId:"31646",year:"2016",episodes:"44 eps (2 seasons)",status:"finished"},
  {title:"PING PONG THE ANIMATION",jp:"ピンポン",rating:4,desc:"Yuasa's masterpiece about friendship and competition.",tags:["sports","drama"],malId:"22135",year:"2014",episodes:"11 eps",status:"finished"},
  {title:"HAJIME NO IPPO",jp:"はじめの一歩",rating:4,desc:"The definitive boxing anime. Pure adrenaline.",tags:["sports","action"],malId:"263",year:"2000",episodes:"75 eps",status:"finished"},
  {title:"SAMURAI CHAMPLOO",jp:"サムライチャンプルー",rating:4,desc:"Anachronistic samurai journey with hip-hop soul.",tags:["action","historical"],malId:"205",year:"2004",episodes:"26 eps",status:"finished"},
  {title:"CODE GEASS",jp:"コードギアス",rating:4,desc:"Exiled prince gains power of absolute obedience.",tags:["action","psychological"],malId:"1575",year:"2006",episodes:"50 eps (2 seasons)",status:"finished"},
  {title:"GURREN LAGANN",jp:"天元突破グレンラガン",rating:4,desc:"Believe in the me that believes in you.",tags:["action","scifi"],malId:"2001",year:"2007",episodes:"27 eps",status:"finished"},
  {title:"HUNTER X HUNTER",jp:"HUNTER×HUNTER",rating:5,desc:"The most intelligent shounen ever written.",tags:["action"],malId:"11061",year:"2011",episodes:"148 eps",status:"finished"},
  {title:"MOB PSYCHO 100",jp:"モブサイコ100",rating:4,desc:"Psychic middle schooler just wants to be normal.",tags:["action","comedy"],malId:"32182",year:"2016",episodes:"37 eps (3 seasons)",status:"finished"},
  {title:"ONE PUNCH MAN",jp:"ワンパンマン",rating:4,desc:"Hero who ends fights in one punch. Satirical genius.",tags:["action","comedy"],malId:"30276",year:"2015",episodes:"24 eps (2 seasons)",status:"airing"},
  {title:"MADE IN ABYSS",jp:"メイドインアビス",rating:4,desc:"Children descend into a beautiful, horrifying abyss.",tags:["fantasy","psychological"],malId:"34599",year:"2017",episodes:"13 eps + movie",status:"airing"},
  {title:"PARASYTE",jp:"寄生獣",rating:4,desc:"Alien parasite takes over a boy's right hand.",tags:["scifi","psychological"],malId:"22535",year:"2014",episodes:"24 eps",status:"finished"},
  {title:"PSYCHO-PASS",jp:"サイコパス",rating:4,desc:"Justice system judges criminals before they act.",tags:["scifi","psychological"],malId:"13601",year:"2012",episodes:"22 eps (S1)",status:"finished"},
  {title:"DEATH PARADE",jp:"デス・パレード",rating:4,desc:"Bartenders judge souls through deadly games.",tags:["psychological","drama"],malId:"28223",year:"2015",episodes:"12 eps",status:"finished"},
  {title:"ERASED",jp:"僕だけがいない街",rating:4,desc:"Man travels back to stop a childhood tragedy.",tags:["psychological","drama"],malId:"31043",year:"2016",episodes:"12 eps",status:"finished"},
  {title:"ODDTAXI",jp:"オッドタクシー",rating:4,desc:"Walrus taxi driver entangled in a missing girl case.",tags:["psychological","drama"],malId:"46102",year:"2021",episodes:"13 eps",status:"finished"},
  {title:"THE TATAMI GALAXY",jp:"四畳半神話大系",rating:4,desc:"Alternate timelines of a college student's regrets.",tags:["psychological","comedy"],malId:"7785",year:"2010",episodes:"11 eps",status:"finished"},
  {title:"SONNY BOY",jp:"サニーボーイ",rating:3,desc:"Students drift through dimensions in existential mystery.",tags:["psychological","scifi"],malId:"48849",year:"2021",episodes:"12 eps",status:"finished"},
  {title:"PLUTO",jp:"プルートウ",rating:4,desc:"Urasawa's Astro Boy reimagining. Robot detective noir.",tags:["scifi","psychological"],malId:"35762",year:"2023",episodes:"8 eps",status:"finished"},
  {title:"CYBERPUNK: EDGERUNNERS",jp:"サイバーパンク エッジランナーズ",rating:4,desc:"Night City chrome. A tragic love letter to cyberpunk.",tags:["action","scifi"],malId:"51535",year:"2022",episodes:"10 eps",status:"finished"},
  {title:"ARCANE",jp:"アーケイン",rating:4,desc:"Masterpiece animation. Sisters torn apart by war.",tags:["action","drama"],malId:"50702",year:"2021",episodes:"9 eps (S1)",status:"airing"},
  {title:"BOCCHI THE ROCK!",jp:"ぼっち・ざ・ろっく！",rating:4,desc:"Socially anxious girl becomes guitar legend.",tags:["comedy","slice-of-life"],malId:"51969",year:"2022",episodes:"12 eps",status:"finished"},
  {title:"SPY X FAMILY",jp:"SPY×FAMILY",rating:4,desc:"Spy, assassin, telepath form a fake family. Wholesome chaos.",tags:["action","comedy"],malId:"50265",year:"2022",episodes:"37 eps (2 seasons)",status:"airing"},
  {title:"BUNGO STRAY DOGS",jp:"文豪ストレイドッグス",rating:4,desc:"Literary authors battle with supernatural abilities.",tags:["action","drama"],malId:"31478",year:"2016",episodes:"60+ eps (5 seasons)",status:"airing"},
  {title:"RE:ZERO",jp:"Re:ゼロから始める異世界生活",rating:4,desc:"Subaru dies again and again to save those he loves.",tags:["psychological","fantasy"],malId:"31240",year:"2016",episodes:"50 eps (2 seasons)",status:"airing"},
  {title:"MUSHOKU TENSEI",jp:"無職転生",rating:4,desc:"A man reborn vows to live without regrets.",tags:["fantasy","drama"],malId:"39535",year:"2021",episodes:"23 eps + OVA",status:"airing"},
  {title:"HELL'S PARADISE",jp:"地獄楽",rating:4,desc:"Criminals sent to paradise island full of horrors.",tags:["action","darkfantasy"],malId:"46569",year:"2023",episodes:"13 eps",status:"airing"},
  {title:"SOLO LEVELING",jp:"俺だけレベルアップな件",rating:3,desc:"Weakest hunter becomes the world's strongest.",tags:["action","fantasy"],malId:"52299",year:"2024",episodes:"12 eps (S1)",status:"airing"},
  {title:"BLUE LOCK",jp:"ブルーロック",rating:4,desc:"Ego-driven football survival. Not your typical sports anime.",tags:["sports","psychological"],malId:"49596",year:"2022",episodes:"24 eps (S1)",status:"airing"},
  {title:"HAIKYUU!!",jp:"ハイキュー!!",rating:4,desc:"Volleyball underdogs soar. Pure hype and heart.",tags:["sports","drama"],malId:"20583",year:"2014",episodes:"85 eps (4 seasons)",status:"finished"},
  {title:"RUN WITH THE WIND",jp:"風が強く吹いている",rating:4,desc:"College students train for a marathon relay.",tags:["sports","drama"],malId:"37965",year:"2018",episodes:"23 eps",status:"finished"},
  {title:"DOROHEDORO",jp:"ドロヘドロ",rating:4,desc:"Lizard-headed amnesiac in a chaotic world.",tags:["action","darkfantasy"],malId:"38668",year:"2020",episodes:"12 eps",status:"finished"},
  {title:"DARKER THAN BLACK",jp:"DARKER THAN BLACK",rating:4,desc:"Contractors with supernatural powers in a dark world.",tags:["action","scifi"],malId:"2025",year:"2007",episodes:"25 eps",status:"finished"},
  {title:"BLACK LAGOON",jp:"ブラック・ラグーン",rating:4,desc:"Salaryman joins mercenaries in the criminal underworld.",tags:["action","psychological"],malId:"889",year:"2006",episodes:"24 eps (2 seasons)",status:"finished"},
  {title:"GREAT TEACHER ONIZUKA",jp:"グレート・ティーチャー・オニヅカ",rating:4,desc:"Ex-biker gang leader becomes the greatest teacher.",tags:["comedy","drama"],malId:"245",year:"1999",episodes:"43 eps",status:"finished"},
  {title:"CLANNAD: AFTER STORY",jp:"クラナド アフターストーリー",rating:4,desc:"Life, love, and devastating loss. The ultimate tear-jerker.",tags:["drama","romance"],malId:"4181",year:"2008",episodes:"24 eps",status:"finished"},
  {title:"ANOHANA",jp:"あの日見た花の名前を僕達はまだ知らない。",rating:4,desc:"Childhood friends reunite to help a ghost move on.",tags:["drama","slice-of-life"],malId:"9989",year:"2011",episodes:"11 eps",status:"finished"},
  {title:"K-ON!",jp:"けいおん！",rating:4,desc:"Light music club. The birth of moe slice-of-life.",tags:["slice-of-life","comedy"],malId:"5680",year:"2009",episodes:"36 eps (2 seasons) + movie",status:"finished"},
  {title:"NICHIIOU",jp:"日常",rating:3,desc:"Absurd surrealist comedy. Deer wrestling. Enough said.",tags:["comedy","slice-of-life"],malId:"10165",year:"2011",episodes:"26 eps",status:"finished"},
  {title:"KONOSUBA",jp:"この素晴らしい世界に祝福を！",rating:4,desc:"Parody isekai. Useless goddess and dysfunctional party.",tags:["comedy","fantasy"],malId:"30831",year:"2016",episodes:"20 eps (2 seasons) + movie",status:"airing"},
  {title:"NANA",jp:"ナナ",rating:4,desc:"Two women named Nana. Punk rock, love, and heartbreak.",tags:["drama","romance"],malId:"877",year:"2006",episodes:"47 eps",status:"finished"},
  {title:"HELLSING ULTIMATE",jp:"ヘルシング",rating:4,desc:"Alucard vs Nazi vampires. Ultimate gore spectacle.",tags:["action","darkfantasy"],malId:"777",year:"2006",episodes:"10 OVAs",status:"finished"},
  {title:"ELVEN LIED",jp:"エルフェンリート",rating:3,desc:"Mutated girl with invisible arms. Bloody and tragic.",tags:["action","psychological"],malId:"226",year:"2004",episodes:"13 eps",status:"finished"},
  {title:"WELCOME TO THE NHK",jp:"N・H・Kにようこそ！",rating:4,desc:"Hikikomori conspiracy theorist's dark spiral.",tags:["psychological","drama"],malId:"1210",year:"2006",episodes:"24 eps",status:"finished"},
  {title:"FLCL",jp:"フリクリ",rating:4,desc:"Batshit insane. Robots from foreheads. Chaos incarnate.",tags:["comedy","scifi"],malId:"227",year:"2000",episodes:"6 eps",status:"finished"},
  {title:"GINTAMA",jp:"銀魂",rating:4,desc:"Legendary comedy. Nothing is sacred. Everything is funny.",tags:["comedy","action"],malId:"918",year:"2006",episodes:"367 eps",status:"finished"},
  {title:"MONONOKE",jp:"モノノ怪",rating:4,desc:"Medicine seller exorcises spirits. Stunning ukiyo-e art.",tags:["psychological","horror"],malId:"2246",year:"2007",episodes:"12 eps",status:"finished"},
  {title:"THE GARDEN OF SINNERS",jp:"空の境界",rating:4,desc:"Girl with mystic death eyes. Dense anime films.",tags:["action","psychological"],malId:"2593",year:"2007",episodes:"8 movies",status:"finished"},
  {title:"SUMMER TIME RENDERING",jp:"サマータイムレンダ",rating:4,desc:"Island time-loop mystery with deadly shadows.",tags:["psychological","scifi"],malId:"47194",year:"2022",episodes:"25 eps",status:"finished"},
  {title:"86",jp:"エイティシックス",rating:4,desc:"Drone pilots fight a war they were never meant to survive.",tags:["action","drama","scifi"],malId:"41457",year:"2021",episodes:"23 eps (2 seasons)",status:"finished"},
  {title:"WIND BREAKER",jp:"ウィンドブレイカー",rating:3,desc:"Delinquent fights to protect his new town.",tags:["action","drama"],malId:"54900",year:"2024",episodes:"13 eps",status:"airing"},
  {title:"KAIJU NO. 8",jp:"怪獣8号",rating:3,desc:"Monster-cleanup worker becomes a kaiju himself.",tags:["action","scifi"],malId:"52158",year:"2024",episodes:"12 eps",status:"airing"},
  {title:"THE APOTHECARY DIARIES",jp:"薬屋のひとりごと",rating:4,desc:"Poison-taster detective in imperial China.",tags:["drama","historical"],malId:"54492",year:"2023",episodes:"24 eps",status:"finished"},
  {title:"UNDEAD UNLUCK",jp:"アンデッドアンラック",rating:3,desc:"Unkillable man meets unluck girl. Wild ride.",tags:["action","comedy"],malId:"51565",year:"2023",episodes:"24 eps",status:"airing"},
  {title:"MASHLE: MAGIC AND MUSCLES",jp:"マッシュル",rating:3,desc:"No magic? Just punch harder. Harry Potter parody.",tags:["comedy","action","fantasy"],malId:"52211",year:"2023",episodes:"24 eps (2 seasons)",status:"airing"},
  {title:"ZOM 100",jp:"ゾン100",rating:3,desc:"Zombie apocalypse bucket list. Colorful and chaotic.",tags:["comedy","action"],malId:"54112",year:"2023",episodes:"12 eps",status:"finished"},
  {title:"TRIGUN STAMPEDE",jp:"TRIGUN STAMPEDE",rating:3,desc:"Vash the Stampede reborn. Stunning CG animation.",tags:["action","scifi"],malId:"52093",year:"2023",episodes:"12 eps",status:"airing"},
  {title:"TO YOUR ETERNITY",jp:"不滅のあなたへ",rating:4,desc:"Immortal being journeys through human experience.",tags:["drama","fantasy"],malId:"41025",year:"2021",episodes:"40 eps (2 seasons)",status:"finished"},
  {title:"GIRLS' LAST TOUR",jp:"少女終末旅行",rating:4,desc:"Two girls wander a post-apocalyptic world.",tags:["slice-of-life","scifi"],malId:"35838",year:"2017",episodes:"12 eps",status:"finished"},
  {title:"PLANETES",jp:"プラネテス",rating:4,desc:"Space debris collectors. Hard sci-fi with soul.",tags:["scifi","drama"],malId:"329",year:"2003",episodes:"26 eps",status:"finished"},
  {title:"TEXHNOLYZE",jp:"テクノライズ",rating:3,desc:"Bleak underground city. Slow descent into nihilism.",tags:["psychological","scifi"],malId:"26",year:"2003",episodes:"22 eps",status:"finished"},
  {title:"PARANOIA AGENT",jp:"妄想代理人",rating:4,desc:"Satoshi Kon's TV masterpiece. Social anxiety incarnate.",tags:["psychological","thriller"],malId:"323",year:"2004",episodes:"13 eps",status:"finished"},
  {title:"RAINBOW",jp:"RAINBOW 二舎六房の七人",rating:4,desc:"Seven delinquents survive brutal reform school.",tags:["drama","historical"],malId:"6114",year:"2010",episodes:"26 eps",status:"finished"},
  {title:"SPACE DANDY",jp:"スペース☆ダンディ",rating:4,desc:"Dandy guy in space. Baby. Pure Watanabe madness.",tags:["comedy","scifi"],malId:"20057",year:"2014",episodes:"26 eps (2 seasons)",status:"finished"},
  {title:"LUPIN THE THIRD: THE WOMAN CALLED FUJIKO MINE",jp:"LUPIN the Third 峰不二子という女",rating:4,desc:"Fujiko Mine origin. Jazz, sex, and thievery.",tags:["action","comedy"],malId:"13203",year:"2012",episodes:"13 eps",status:"finished"},
  {title:"ANGEL BEATS!",jp:"Angel Beats!",rating:4,desc:"Afterlife school rebellion. Emotional gut-punch.",tags:["drama","action"],malId:"6547",year:"2010",episodes:"13 eps",status:"finished"},
  {title:"NO GAME NO LIFE",jp:"ノーゲーム・ノーライフ",rating:4,desc:"Siblings conquer a world through games.",tags:["fantasy","comedy"],malId:"19815",year:"2014",episodes:"12 eps + movie",status:"finished"},
  {title:"KILL LA KILL",jp:"キルラキル",rating:4,desc:"Clothing-powered battles. Pure Trigger insanity.",tags:["action","comedy"],malId:"18679",year:"2013",episodes:"24 eps",status:"finished"},
  {title:"AKAME GA KILL!",jp:"アカメが斬る！",rating:3,desc:"Assassins vs corrupt empire. Nobody is safe.",tags:["action","darkfantasy"],malId:"22199",year:"2014",episodes:"24 eps",status:"finished"},
  {title:"NORAGAMI",jp:"ノラガミ",rating:4,desc:"Stray god does odd jobs for 5 yen.",tags:["action","comedy"],malId:"20507",year:"2014",episodes:"25 eps (2 seasons)",status:"finished"},
  {title:"SHINSEKAI YORI",jp:"新世界より",rating:4,desc:"Dystopian future with psychic children. Slow-burn dread.",tags:["psychological","scifi"],malId:"13125",year:"2012",episodes:"25 eps",status:"finished"}
];
var mangaDB=[
  {title:"BERSERK",jp:"ベルセルク",rating:5,desc:"Miura's dark fantasy opus. Guts vs fate.",tags:["darkfantasy","action","seinen"],malId:"2",year:"1989",episodes:"364+ chapters",status:"airing"},
  {title:"VAGABOND",jp:"バガボンド",rating:5,desc:"Musashi's journey. Inoue's art is god-tier.",tags:["historical","action","seinen"],malId:"11",year:"1998",episodes:"327 chapters",status:"airing"},
  {title:"GOODNIGHT PUNPUN",jp:"おやすみプンプン",rating:5,desc:"Asano's masterpiece about depression and growing up.",tags:["psychological","drama","seinen"],malId:"31658",year:"2007",episodes:"147 chapters",status:"finished"},
  {title:"CLAYMORE",jp:"クレイモア",rating:4,desc:"Female warriors vs monsters. Underrated gem.",tags:["darkfantasy","action","seinen"],malId:"583",year:"2001",episodes:"159 chapters",status:"finished"},
  {title:"BLAME!",jp:"ブラム！",rating:4,desc:"Silent, vast, industrial nightmare. Nihei's magnum opus.",tags:["scifi","action","seinen"],malId:"283",year:"1997",episodes:"66 chapters",status:"finished"},
  {title:"THE CLIMBER",jp:"孤高の人",rating:5,desc:"Psychological mountain climbing. Hidden gem of seinen.",tags:["psychological","sports","seinen"],malId:"13160",year:"2007",episodes:"170 chapters",status:"finished"},
  {title:"MONSTER",jp:"モンスター",rating:5,desc:"Urasawa's thriller manga masterpiece.",tags:["psychological","thriller","seinen"],malId:"593",year:"1994",episodes:"162 chapters",status:"finished"},
  {title:"KINGDOM",jp:"キングダム",rating:4,desc:"Warring States era China. Epic battle strategy.",tags:["action","historical","seinen"],malId:"1074",year:"2006",episodes:"800+ chapters",status:"airing"},
  {title:"MOMOSE AKIRA",jp:"桃瀬アキラ",rating:4,desc:"Peak romcom. Akira is best girl.",tags:["romance","comedy"],malId:"162371",year:"2022",episodes:"80+ chapters",status:"airing"},
  {title:"FRAGRANT FLOWER BLOOMS WITH DIGNITY",jp:"薫る花は凛と咲く",rating:4,desc:"Rival school romance done perfectly.",tags:["romance","slice-of-life"],malId:"158925",year:"2021",episodes:"130+ chapters",status:"airing"},
  {title:"20TH CENTURY BOYS",jp:"20世紀少年",rating:5,desc:"Cult prophecy comes true. Urasawa's epic mystery.",tags:["psychological","thriller","seinen"],malId:"3",year:"1999",episodes:"249 chapters",status:"finished"},
  {title:"PLUTO",jp:"プルートウ",rating:4,desc:"Robot detective investigates serial murders.",tags:["scifi","psychological","seinen"],malId:"745",year:"2003",episodes:"65 chapters",status:"finished"},
  {title:"BILLY BAT",jp:"ビリーバット",rating:4,desc:"A comic artist drawn into global conspiracy.",tags:["psychological","historical","seinen"],malId:"15701",year:"2008",episodes:"165 chapters",status:"finished"},
  {title:"SOLANIN",jp:"ソラニン",rating:4,desc:"Post-college ennui. Asano at his most relatable.",tags:["drama","slice-of-life","seinen"],malId:"15693",year:"2005",episodes:"28 chapters",status:"finished"},
  {title:"HOMUNCULUS",jp:"ホムンクルス",rating:4,desc:"Homeless man drills hole in skull. Sees monsters.",tags:["psychological","horror","seinen"],malId:"1408",year:"2003",episodes:"166 chapters",status:"finished"},
  {title:"AKIRA",jp:"アキラ",rating:5,desc:"Otomo's magnum opus. Neo-Tokyo explodes.",tags:["scifi","action","seinen"],malId:"664",year:"1982",episodes:"120 chapters",status:"finished"},
  {title:"GHOST IN THE SHELL",jp:"攻殻機動隊",rating:4,desc:"The definitive cyberpunk manga.",tags:["scifi","psychological","seinen"],malId:"1023",year:"1989",episodes:"53 chapters",status:"finished"},
  {title:"LONE WOLF AND CUB",jp:"子連れ狼",rating:4,desc:"Samurai and toddler on a path of vengeance.",tags:["historical","action","seinen"],malId:"325",year:"1970",episodes:"142 chapters",status:"finished"},
  {title:"BLADE OF THE IMMORTAL",jp:"無限の住人",rating:4,desc:"Immortal samurai seeks to kill 1000 evil men.",tags:["action","historical","seinen"],malId:"17",year:"1993",episodes:"206 chapters",status:"finished"},
  {title:"VINLAND SAGA",jp:"ヴィンランド・サガ",rating:5,desc:"Viking revenge saga that becomes a meditation on peace.",tags:["action","historical","seinen"],malId:"642",year:"2005",episodes:"210+ chapters",status:"airing"},
  {title:"DOROHEDORO",jp:"ドロヘドロ",rating:4,desc:"Lizard head guy in a magic vs muscle world.",tags:["action","darkfantasy","seinen"],malId:"1133",year:"2000",episodes:"167 chapters",status:"finished"},
  {title:"DAI DARK",jp:"大ダーク",rating:4,desc:"Boy with dark power. Same author as Dorohedoro.",tags:["darkfantasy","comedy","seinen"],malId:"118168",year:"2019",episodes:"50+ chapters",status:"airing"},
  {title:"CHAINSAW MAN",jp:"チェンソーマン",rating:4,desc:"Fujimoto's wild ride. Denji just wants normal life.",tags:["action","darkfantasy"],malId:"116778",year:"2018",episodes:"180+ chapters",status:"airing"},
  {title:"FIRE PUNCH",jp:"ファイアパンチ",rating:4,desc:"Man on fire seeks revenge in frozen wasteland.",tags:["darkfantasy","psychological"],malId:"101091",year:"2016",episodes:"83 chapters",status:"finished"},
  {title:"GOODBYE ERI",jp:"さよなら絵梨",rating:4,desc:"Fujimoto's one-shot about film and grief.",tags:["drama","psychological"],malId:"148465",year:"2022",episodes:"1 volume (one-shot)",status:"finished"},
  {title:"LOOK BACK",jp:"ルックバック",rating:4,desc:"Two girls bond over manga. Fujimoto's most personal work.",tags:["drama","slice-of-life"],malId:"143447",year:"2021",episodes:"1 volume (one-shot)",status:"finished"},
  {title:"TOKYO GHOUL",jp:"東京喰種",rating:4,desc:"Half-ghoul struggles between human and monster worlds.",tags:["darkfantasy","action"],malId:"33327",year:"2011",episodes:"143 chapters",status:"finished"},
  {title:"GANTZ",jp:"ガンツ",rating:4,desc:"Dead people forced to hunt aliens. Brutal sci-fi.",tags:["scifi","action","seinen"],malId:"122",year:"2000",episodes:"383 chapters",status:"finished"},
  {title:"INUYASHIKI",jp:"いぬやしき",rating:4,desc:"Elderly man becomes cyborg hero. Same author as Gantz.",tags:["scifi","drama","seinen"],malId:"90771",year:"2014",episodes:"85 chapters",status:"finished"},
  {title:"AJIN",jp:"亜人",rating:4,desc:"Immortal demi-humans hunted by government.",tags:["action","psychological","seinen"],malId:"76789",year:"2012",episodes:"86 chapters",status:"finished"},
  {title:"THE FABLE",jp:"ザ・ファブル",rating:4,desc:"Legendary hitman ordered to live normally.",tags:["action","comedy","seinen"],malId:"101631",year:"2014",episodes:"240 chapters",status:"finished"},
  {title:"I AM A HERO",jp:"アイアムアヒーロー",rating:4,desc:"Manga artist survives realistic zombie apocalypse.",tags:["horror","psychological","seinen"],malId:"25146",year:"2009",episodes:"264 chapters",status:"finished"},
  {title:"UZUMAKI",jp:"うずまき",rating:4,desc:"Ito's spiral nightmare. Town consumed by patterns.",tags:["horror","psychological","seinen"],malId:"541",year:"1998",episodes:"19 chapters",status:"finished"},
  {title:"TOMIE",jp:"富江",rating:4,desc:"Ito's immortal succubus. Beautiful and terrifying.",tags:["horror","psychological"],malId:"540",year:"1987",episodes:"20 chapters",status:"finished"},
  {title:"THE ENIGMA OF AMIGARA FAULT",jp:"阿弥殻断層の怪",rating:4,desc:"Ito's best short. Human-shaped holes in mountain.",tags:["horror","psychological"],malId:"38333",year:"2001",episodes:"1 chapter (one-shot)",status:"finished"},
  {title:"DEAD DEAD DEMON'S DEDEDEDE DESTRUCTION",jp:"デッドデッドデーモンズデデデデデストラクション",rating:4,desc:"Asano's alien invasion slice-of-life. Masterful.",tags:["scifi","drama","seinen"],malId:"79625",year:"2014",episodes:"100 chapters",status:"finished"},
  {title:"YOTSUBA&!",jp:"よつばと！",rating:4,desc:"Green-haired girl discovers the world. Pure joy.",tags:["comedy","slice-of-life"],malId:"28",year:"2003",episodes:"100+ chapters",status:"airing"},
  {title:"AZUMANGA DAIOH",jp:"あずまんが大王",rating:4,desc:"High school girls and Osaka's absurd humor.",tags:["comedy","slice-of-life"],malId:"13",year:"1999",episodes:"69 chapters",status:"finished"},
  {title:"NICHIJOU",jp:"日常",rating:3,desc:"Surreal comedy. Deer wrestling. Robot girl.",tags:["comedy","slice-of-life"],malId:"2834",year:"2006",episodes:"192 chapters",status:"finished"},
  {title:"GRAND BLUE DREAMING",jp:"ぐらんぶる",rating:4,desc:"Diving club manga. Mostly drinking. Pure chaos.",tags:["comedy","slice-of-life"],malId:"94601",year:"2014",episodes:"90+ chapters",status:"airing"},
  {title:"SPY X FAMILY",jp:"SPY×FAMILY",rating:3,desc:"Spy, assassin, telepath form fake family.",tags:["action","comedy"],malId:"119161",year:"2019",episodes:"100+ chapters",status:"airing"},
  {title:"KAGUYA-SAMA: LOVE IS WAR",jp:"かぐや様は告らせたい",rating:5,desc:"Geniuses play mind games to avoid confessing.",tags:["romance","comedy"],malId:"89667",year:"2015",episodes:"281 chapters",status:"finished"},
  {title:"HORIMIYA",jp:"ホリミヤ",rating:4,desc:"Gap-moe romance done right.",tags:["romance","slice-of-life"],malId:"42451",year:"2011",episodes:"122 chapters",status:"finished"},
  {title:"AO HARU RIDE",jp:"アオハライド",rating:3,desc:"First love rekindled. Peak shoujo romance.",tags:["romance","drama","slice-of-life"],malId:"24271",year:"2011",episodes:"49 chapters",status:"finished"},
  {title:"ORANGE",jp:"オレンジ",rating:4,desc:"Letters from the future to save a friend.",tags:["romance","drama","slice-of-life"],malId:"66349",year:"2012",episodes:"22 chapters",status:"finished"},
  {title:"KIMI NI TODOKE",jp:"君に届け",rating:4,desc:"Misunderstood girl finds friendship and love.",tags:["romance","slice-of-life"],malId:"689",year:"2005",episodes:"123 chapters",status:"finished"},
  {title:"LOVE IS HARD FOR OTAKU",jp:"ヲタクに恋は難しい",rating:4,desc:"Two otaku navigate dating. Relatable chaos.",tags:["romance","comedy"],malId:"99119",year:"2015",episodes:"100+ chapters",status:"airing"},
  {title:"THE HORIZON",jp:"地平線",rating:5,desc:"Two children walk through a war-torn world.",tags:["drama","psychological"],malId:"121250",year:"2016",episodes:"21 chapters",status:"finished"},
  {title:"MONSTER CHILD",jp:"怪物事変",rating:3,desc:"Boy raised by monsters investigates supernatural cases.",tags:["action","fantasy"],malId:"103229",year:"2017",episodes:"70+ chapters",status:"airing"},
  {title:"DANDADAN",jp:"ダンダダン",rating:4,desc:"Ghosts, aliens, stolen balls. Absolute insanity.",tags:["action","romance","comedy"],malId:"143281",year:"2021",episodes:"170+ chapters",status:"airing"},
  {title:"SAKAMOTO DAYS",jp:"サカモトデイズ",rating:4,desc:"Retired legendary hitman runs a convenience store.",tags:["action","comedy"],malId:"136787",year:"2020",episodes:"180+ chapters",status:"airing"},
  {title:"KAIJU NO. 8",jp:"怪獣8号",rating:3,desc:"Cleanup worker becomes a kaiju. Epic scale.",tags:["action","scifi"],malId:"120085",year:"2020",episodes:"110+ chapters",status:"airing"},
  {title:"BLUE BOX",jp:"アオのハコ",rating:4,desc:"Badminton boy falls for basketball girl. Sports romance.",tags:["romance","sports"],malId:"138227",year:"2021",episodes:"170+ chapters",status:"airing"},
  {title:"AKANE BANASHI",jp:"あかね噺",rating:4,desc:"Girl aims to master rakugo storytelling art.",tags:["drama","slice-of-life"],malId:"154142",year:"2022",episodes:"130+ chapters",status:"airing"},
  {title:"THE 100 GIRLFRIENDS WHO REALLY LOVE YOU",jp:"君のことが大大大大大好きな100人の彼女",rating:3,desc:"Every girlfriend matters. Harem parody masterpiece.",tags:["comedy","romance"],malId:"131570",year:"2019",episodes:"190+ chapters",status:"airing"},
  {title:"ONE PUNCH MAN",jp:"ワンパンマン",rating:4,desc:"Murata's god-tier art. Saitama ends fights in one punch.",tags:["action","comedy"],malId:"44347",year:"2012",episodes:"200+ chapters",status:"airing"},
  {title:"MOB PSYCHO 100",jp:"モブサイコ100",rating:4,desc:"Psychic boy just wants to be normal. ONE's masterpiece.",tags:["action","comedy","psychological"],malId:"77785",year:"2012",episodes:"101 chapters",status:"finished"},
  {title:"HOUSEKI NO KUNI",jp:"宝石の国",rating:4,desc:"Gem people fight moon dwellers. Existential suffering.",tags:["action","psychological","fantasy"],malId:"83781",year:"2012",episodes:"108 chapters",status:"airing"},
  {title:"GOLDEN KAMUY",jp:"ゴールデンカムイ",rating:4,desc:"Treasure hunt with Ainu culture. Wild and educational.",tags:["action","historical","seinen"],malId:"85968",year:"2014",episodes:"314 chapters",status:"finished"},
  {title:"DUNGEON MESHI",jp:"ダンジョン飯",rating:5,desc:"Cooking monsters in a dungeon. Delicious worldbuilding.",tags:["fantasy","comedy","seinen"],malId:"87517",year:"2014",episodes:"97 chapters",status:"finished"},
  {title:"HELL'S PARADISE",jp:"地獄楽",rating:4,desc:"Criminals on death row hunt for immortality elixir.",tags:["action","darkfantasy"],malId:"106479",year:"2018",episodes:"127 chapters",status:"finished"},
  {title:"TOKYO REVENGERS",jp:"東京卍リベンジャーズ",rating:3,desc:"Loser goes back in time to save his girlfriend.",tags:["action","drama"],malId:"119119",year:"2017",episodes:"278 chapters",status:"finished"},
  {title:"BLUE LOCK",jp:"ブルーロック",rating:4,desc:"Egoist footballers compete to be the best striker.",tags:["sports","psychological"],malId:"132290",year:"2018",episodes:"270+ chapters",status:"airing"},
  {title:"SLAM DUNK",jp:"スラムダンク",rating:5,desc:"The legendary basketball manga. Delinquent becomes ace.",tags:["sports","comedy"],malId:"4",year:"1990",episodes:"276 chapters",status:"finished"},
  {title:"REAL",jp:"リアル",rating:4,desc:"Inoue's wheelchair basketball drama. Raw and human.",tags:["sports","drama","seinen"],malId:"743",year:"1999",episodes:"90+ chapters",status:"airing"},
  {title:"HAJIME NO IPPO",jp:"はじめの一歩",rating:4,desc:"The greatest boxing manga ever. 30+ years strong.",tags:["sports","action"],malId:"7",year:"1989",episodes:"1400+ chapters",status:"airing"},
  {title:"ASHITA NO JOE",jp:"あしたのジョー",rating:5,desc:"Classic boxing tragedy. Burned to pure white ash.",tags:["sports","drama"],malId:"80",year:"1968",episodes:"171 chapters",status:"finished"},
  {title:"PROMISED NEVERLAND",jp:"約束のネバーランド",rating:4,desc:"Children escape their orphanage farm. Gripping thriller.",tags:["psychological","thriller"],malId:"98415",year:"2016",episodes:"181 chapters",status:"finished"},
  {title:"SHADOW HOUSE",jp:"シャドーハウス",rating:4,desc:"Living dolls serve shadow nobles. Gothic mystery.",tags:["mystery","fantasy","seinen"],malId:"120136",year:"2018",episodes:"180+ chapters",status:"airing"},
  {title:"SUMMER TIME RENDERING",jp:"サマータイムレンダ",rating:4,desc:"Island time-loop thriller with doppelgangers.",tags:["psychological","thriller"],malId:"119143",year:"2017",episodes:"139 chapters",status:"finished"},
  {title:"HAPPINESS",jp:"ハピネス",rating:4,desc:"Shuzo Oshimi's vampire coming-of-age horror.",tags:["horror","psychological"],malId:"95615",year:"2015",episodes:"50 chapters",status:"finished"},
  {title:"CHI NO WADACHI",jp:"血の轍",rating:4,desc:"Mother's psychological grip destroys her son. Oshimi's best.",tags:["psychological","drama","seinen"],malId:"117271",year:"2017",episodes:"153 chapters",status:"finished"},
  {title:"INSIDE MARI",jp:"ぼくは麻理のなか",rating:4,desc:"Man wakes up in a high school girl's body.",tags:["psychological","drama","seinen"],malId:"52137",year:"2012",episodes:"80 chapters",status:"finished"},
  {title:"FLOWERS OF EVIL",jp:"惡の華",rating:4,desc:"Middle school boy steals gym clothes. Descent into deviance.",tags:["psychological","drama"],malId:"25515",year:"2009",episodes:"57 chapters",status:"finished"},
  {title:"BOYS ABYSS",jp:"少年のアビス",rating:3,desc:"Small town traps everyone in cycle of despair.",tags:["psychological","drama","seinen"],malId:"135507",year:"2020",episodes:"180+ chapters",status:"airing"},
  {title:"A GIRL ON THE SHORE",jp:"うみべの女の子",rating:4,desc:"Asano's raw exploration of teenage sexuality.",tags:["drama","psychological","seinen"],malId:"22838",year:"2009",episodes:"20 chapters",status:"finished"},
  {title:"NANA TO KAORU",jp:"ナナとカオル",rating:4,desc:"Childhood friends explore BDSM. Surprisingly wholesome.",tags:["romance","psychological","seinen"],malId:"756",year:"2008",episodes:"156 chapters",status:"finished"},
  {title:"MY DEAREST SELF WITH MALICE AFORE THOUGHT",jp:"親愛なる僕へ殺意をこめて",rating:4,desc:"Son of a serial killer. Mind-bending thriller.",tags:["psychological","thriller"],malId:"116648",year:"2018",episodes:"97 chapters",status:"finished"},
  {title:"JAGAAAAAN",jp:"ジャガーン",rating:3,desc:"Frog parasite gives powers. Gory and dark.",tags:["action","darkfantasy","seinen"],malId:"108234",year:"2017",episodes:"160+ chapters",status:"airing"},
  {title:"MADE IN ABYSS",jp:"メイドインアビス",rating:4,desc:"Children descend into beautiful hell. Unforgiving.",tags:["fantasy","psychological"],malId:"91969",year:"2012",episodes:"60+ chapters",status:"airing"},
  {title:"THE BREAKER",jp:"THE BREAKER",rating:4,desc:"Bullied boy learns martial arts. Korean action peak.",tags:["action","martialarts"],malId:"858",year:"2007",episodes:"72 chapters",status:"finished"},
  {title:"THE BREAKER: NEW WAVES",jp:"THE BREAKER: NEW WAVES",rating:4,desc:"Continuation. Bigger scale, higher stakes.",tags:["action","martialarts"],malId:"29651",year:"2010",episodes:"201 chapters",status:"finished"},
  {title:"VERITAS",jp:"베리타스",rating:4,desc:"Martial arts school. Lightning powers. Cancelled too soon.",tags:["action","martialarts"],malId:"13915",year:"2005",episodes:"81 chapters",status:"finished"},
  {title:"SHAMAN KING",jp:"シャーマンキング",rating:3,desc:"Shaman tournament to become the Shaman King.",tags:["action","fantasy"],malId:"27",year:"1998",episodes:"300 chapters",status:"finished"},
  {title:"SOUL EATER",jp:"ソウルイーター",rating:4,desc:"Weapons and meisters hunt evil souls. Stylish.",tags:["action","fantasy"],malId:"167",year:"2003",episodes:"113 chapters",status:"finished"},
  {title:"DEATH NOTE",jp:"デスノート",rating:4,desc:"The definitive psychological thriller manga.",tags:["psychological","thriller"],malId:"21",year:"2003",episodes:"108 chapters",status:"finished"},
  {title:"BAKUMAN",jp:"バクマン。",rating:4,desc:"Two boys chase their dream of becoming manga artists.",tags:["comedy","drama"],malId:"585",year:"2008",episodes:"176 chapters",status:"finished"},
  {title:"ASSASSINATION CLASSROOM",jp:"暗殺教室",rating:4,desc:"Students must assassinate their alien teacher.",tags:["comedy","action"],malId:"79437",year:"2012",episodes:"180 chapters",status:"finished"},
  {title:"DR. STONE",jp:"Dr.STONE",rating:4,desc:"Science genius rebuilds civilization from scratch.",tags:["scifi","comedy"],malId:"103897",year:"2017",episodes:"232 chapters",status:"finished"},
  {title:"BEASTARS",jp:"BEASTARS",rating:4,desc:"Wolf struggles with his instincts in animal society.",tags:["drama","psychological"],malId:"103647",year:"2016",episodes:"196 chapters",status:"finished"},
  {title:"WITCH HAT ATELIER",jp:"とんがり帽子のアトリエ",rating:4,desc:"Girl learns magic in the most beautifully drawn world.",tags:["fantasy","slice-of-life"],malId:"108451",year:"2016",episodes:"80+ chapters",status:"airing"},
  {title:"MAGUS OF THE LIBRARY",jp:"圕の大魔術師",rating:4,desc:"Boy dreams of becoming a librarian. Fantasy adventure.",tags:["fantasy","drama"],malId:"106319",year:"2017",episodes:"30+ chapters",status:"airing"},
  {title:"FRIEREN: BEYOND JOURNEY'S END",jp:"葬送のフリーレン",rating:5,desc:"Elf learns what it means to live after the hero dies.",tags:["fantasy","drama"],malId:"126288",year:"2020",episodes:"130+ chapters",status:"airing"},
  {title:"THE APOTHECARY DIARIES",jp:"薬屋のひとりごと",rating:4,desc:"Poison fanatic detective in imperial China.",tags:["drama","historical"],malId:"123068",year:"2017",episodes:"70+ chapters",status:"airing"}
];
var manhwaDB=[
  {title:"OMNISCIENT READER'S VIEWPOINT",jp:"전지적 독자 시점",rating:5,desc:"A novel reader's world becomes reality. Peak Korean fiction.",tags:["action","psychological"],malId:"110150",year:"2020",episodes:"220+ chapters",status:"airing"},
  {title:"TOWER OF GOD",jp:"신의 탑",rating:4,desc:"Climb the tower. One of the greatest manhwa ever made.",tags:["action","adventure"],malId:"25639",year:"2010",episodes:"640+ chapters",status:"airing"},
  {title:"SSS-CLASS SUICIDE HUNTER",jp:"SSS급 자살헌터",rating:4,desc:"Dying to get stronger. Psychological masterpiece.",tags:["action","fantasy","psychological"],malId:"148810",year:"2021",episodes:"100+ chapters",status:"airing"},
  {title:"SWEET HOME",jp:"스위트홈",rating:4,desc:"Monsters manifested from desire. Haunting and brilliant.",tags:["horror","psychological"],malId:"116226",year:"2017",episodes:"141 chapters",status:"finished"},
  {title:"BASTARD",jp:"버스타드",rating:4,desc:"Boy with serial killer father. Tense psychological thriller.",tags:["psychological","thriller"],malId:"110170",year:"2014",episodes:"94 chapters",status:"finished"},
  {title:"THE BOXER",jp:"더 복서",rating:4,desc:"Boxing with deep psychology. Best sports manhwa.",tags:["action","sports","psychological"],malId:"137221",year:"2019",episodes:"130 chapters",status:"finished"},
  {title:"SOLO LEVELING",jp:"나 혼자만 레벨업",rating:4,desc:"Weakest hunter becomes the world's strongest. Iconic.",tags:["action","fantasy"],malId:"121496",year:"2018",episodes:"179 chapters",status:"finished"},
  {title:"THE BEGINNING AFTER THE END",jp:"끝나지 않는 시작",rating:4,desc:"King reborn in fantasy world. Builds power from childhood.",tags:["action","fantasy"],malId:"132638",year:"2018",episodes:"180+ chapters",status:"airing"},
  {title:"NORTHERN BLADE",jp:"북검전기",rating:4,desc:"Last disciple of a destroyed sect. Murim revenge epic.",tags:["action","historical"],malId:"139067",year:"2019",episodes:"160+ chapters",status:"airing"},
  {title:"DOOM BREAKER",jp:"파멸의 기사",rating:4,desc:"Last human returns to save the world. Dragon slaying.",tags:["action","fantasy"],malId:"151144",year:"2021",episodes:"90+ chapters",status:"airing"},
  {title:"GOD OF HIGHSCHOOL",jp:"갓 오브 하이스쿨",rating:3,desc:"Martial arts tournament. Borrowed powers. Insane action.",tags:["action","fantasy"],malId:"108576",year:"2011",episodes:"569 chapters",status:"finished"},
  {title:"HARD CARRY SUPPORT",jp:"하드캐리 서포트",rating:3,desc:"Game support class becomes the ultimate carry.",tags:["action","fantasy"],malId:"154739",year:"2021",episodes:"100+ chapters",status:"airing"},
  {title:"TRASH OF THE COUNT'S FAMILY",jp:"백작가의 망나니",rating:4,desc:"Reincarnated as a villain in a novel. Builds a family.",tags:["fantasy","drama"],malId:"133123",year:"2020",episodes:"120+ chapters",status:"airing"},
  {title:"ELECEED",jp:"일렉시드",rating:4,desc:"Cat lover with super speed. Best power system.",tags:["action","fantasy"],malId:"119835",year:"2018",episodes:"280+ chapters",status:"airing"},
  {title:"WIND BREAKER",jp:"윈드브레이커",rating:4,desc:"High school cycling crew. Sports manhwa at its peak.",tags:["sports","drama"],malId:"122454",year:"2015",episodes:"450+ chapters",status:"airing"},
  {title:"LOOKISM",jp:"외모지상주의",rating:4,desc:"Fat boy gets a perfect body. Gang wars and philosophy.",tags:["action","drama"],malId:"116139",year:"2014",episodes:"470+ chapters",status:"airing"},
  {title:"UNORDINARY",jp:"언오디너리",rating:3,desc:"Powerless boy in superpower school. Hidden king.",tags:["action","psychological"],malId:"128623",year:"2016",episodes:"310+ chapters",status:"airing"},
  {title:"THE GOD OF PRO TO WRESTLING",jp:"프로레슬링의 신",rating:4,desc:"Retired wrestler returns to the ring. Gritty and raw.",tags:["sports","drama"],malId:"163000",year:"2022",episodes:"80+ chapters",status:"airing"},
  {title:"CHILDHOOD FRIEND OF THE ZENITH",jp:"천하제일인의 소꿉친구",rating:3,desc:"Murim legend returns to protect his childhood friend.",tags:["action","historical","fantasy"],malId:"164000",year:"2023",episodes:"50+ chapters",status:"airing"},
  {title:"RETURN OF THE MOUNT HUA SECT",jp:"화산귀환",rating:4,desc:"Sword master reborn to revive fallen sect. Comedy and action.",tags:["action","comedy","historical"],malId:"147845",year:"2019",episodes:"120+ chapters",status:"airing"},
  {title:"NANO MACHINE",jp:"나노머신",rating:3,desc:"Prince gains nano technology in murim world.",tags:["action","scifi","historical"],malId:"147098",year:"2020",episodes:"180+ chapters",status:"airing"},
  {title:"RETURN OF THE DISASTER-CLASS HERO",jp:"재앙급 영웅님이 귀환하셨다",rating:3,desc:"Betrayed hero returns to wreak havoc.",tags:["action","fantasy"],malId:"151039",year:"2021",episodes:"80+ chapters",status:"airing"},
  {title:"A RETURNER'S MAGIC SHOULD BE SPECIAL",jp:"귀환자의 마법은 특별해야 합니다",rating:4,desc:"Last survivor returns to prevent the apocalypse.",tags:["action","fantasy"],malId:"129646",year:"2018",episodes:"250+ chapters",status:"airing"},
  {title:"THE GREAT MAGE RETURNS AFTER 4000 YEARS",jp:"4000년 만에 귀환한 대마도사",rating:3,desc:"Archmage wakes up in modern world. Defeats gods.",tags:["action","fantasy"],malId:"133557",year:"2020",episodes:"180+ chapters",status:"airing"},
  {title:"KILL THE HERO",jp:"킬 더 히어로",rating:3,desc:"Betrayed by his guild leader. Revenge from the start.",tags:["action","psychological"],malId:"138206",year:"2020",episodes:"140+ chapters",status:"finished"},
  {title:"THE PLAYER WHO CAN'T LEVEL UP",jp:"레벨업 못하는 플레이어",rating:3,desc:"Stuck at level 1. Unlocks hidden power system.",tags:["action","fantasy"],malId:"149800",year:"2021",episodes:"120+ chapters",status:"airing"},
  {title:"OVERGEARED",jp:"오버기어드",rating:4,desc:"Blacksmith player finds legendary class. VR epic.",tags:["action","fantasy"],malId:"130388",year:"2020",episodes:"190+ chapters",status:"airing"},
  {title:"THE TUTORIAL IS TOO HARD",jp:"튜토리얼이 너무 어렵다",rating:3,desc:"Pro gamer chooses hell difficulty. Suffers beautifully.",tags:["action","fantasy"],malId:"146013",year:"2021",episodes:"90+ chapters",status:"airing"},
  {title:"MAGIC EMPEROR",jp:"마제",rating:3,desc:"Demon emperor reincarnated as servant boy. Ruthless.",tags:["action","psychological","fantasy"],malId:"140970",year:"2019",episodes:"400+ chapters",status:"airing"},
  {title:"MEMOIR OF THE KING OF WAR",jp:"무왕의 회고록",rating:4,desc:"Legendary warrior's past revealed. Art is breathtaking.",tags:["action","historical"],malId:"147300",year:"2020",episodes:"130+ chapters",status:"airing"},
  {title:"BLADE OF THE PHANTOM MASTER",jp:"환마검",rating:3,desc:"Exorcist with phantom blade. Dark fantasy meets action.",tags:["action","fantasy","darkfantasy"],malId:"158000",year:"2022",episodes:"80+ chapters",status:"airing"},
  {title:"SECOND LIFE RANKER",jp:"세컨드 라이프 랭커",rating:3,desc:"Twin brother climbs tower for revenge.",tags:["action","fantasy"],malId:"138942",year:"2019",episodes:"160+ chapters",status:"airing"},
  {title:"THE MAX LEVEL HERO HAS RETURNED",jp:"만렙 영웅님 께서 귀환 하신다",rating:3,desc:"Hero returns as prince. Builds kingdom.",tags:["fantasy","action"],malId:"147500",year:"2020",episodes:"120+ chapters",status:"airing"},
  {title:"LEVELING WITH THE GODS",jp:"신들과 함께 레벨업",rating:3,desc:"Climb the tower with mythological gods.",tags:["action","fantasy"],malId:"155100",year:"2021",episodes:"100+ chapters",status:"airing"}
];

var musashiQ=[
  {t:"You must understand that there is more than one path to the top of the mountain.",s:"— 五輪書"},
  {t:"Think lightly of yourself and deeply of the world.",s:"— 独行道 (Dokkōdō, 21 Precepts)"},
  {t:"Perceive that which cannot be seen with the eye.",s:"— 五輪書"},
  {t:"The true science of martial arts means practicing them in such a way that they will be useful at any time.",s:"— 五輪書"},
  {t:"If you know the way broadly, you will see it in all things.",s:"— 五輪書"},
  {t:"There is nothing outside of yourself that can enable you to get better.",s:"— 独行道"},
  {t:"Whatever you do, do it with the proper spirit. Practice always.",s:"— 五輪書"},
  {t:"The way of the warrior is the resolute acceptance of death.",s:"— 五輪書"}
];
